apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  namespace: jenkins
  labels:
    app: jenkins-app
spec:
  selector:
    app: jenkins-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
