apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  labels:
    app: jenkins-app
spec:
  selector:
    app: jenkins-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32000
